#!/usr/bin/env python3
"""Bundle orbit_ui for the Orbit pedal's web server.

Reads the plain files the page uses, trims Ambient CSS to the rules the page
actually references, gzips each file and writes ONE header with a route table
for the firmware (orbit/src/web_bundle.h), plus a dist/ folder holding the
trimmed files so the exact bundle can be served locally and eyeballed.

    python3 tools/bundle.py [--out ../orbit/src/web_bundle.h] [--dist dist]

No build step otherwise: the files ship as they are on GitHub Pages, minus the
"?v=" cache-busters (the firmware version is the cache key on the pedal).
"""
import argparse, gzip, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILES = [  # (route, source, mime)
    ('/',                'index.html',      'text/html'),
    ('/orbit.css',       'orbit.css',       'text/css'),
    ('/gc.css',          'gc.css',          'text/css'),
    ('/ambient.css',     'ambient.css',     'text/css'),
    ('/link.js',         'link.js',         'application/javascript'),
    ('/program.js',      'program.js',      'application/javascript'),
    ('/gc/protocol.js',  'gc/protocol.js',  'application/javascript'),
    ('/gc/effects.js',   'gc/effects.js',   'application/javascript'),
    ('/gc/curve.js',     'gc/curve.js',     'application/javascript'),
    ('/gc/factory.js',   'gc/factory.js',   'application/javascript'),
    ('/gc/sim.js',       'gc/sim.js',       'application/javascript'),
    ('/gc/tab.js',       'gc/tab.js',       'application/javascript'),
    ('/pedal.js',        'pedal.js',        'application/javascript'),
    ('/orbit.js',        'orbit.js',        'application/javascript'),
]

def read(rel):
    with open(os.path.join(ROOT, rel), 'rb') as f:
        return f.read()

def used_ambient_classes():
    """Every amb-* / ambx-* / ambient class the page's markup or scripts mention."""
    text = b''.join(read(src) for _, src, _ in FILES if not src.endswith('ambient.css')).decode('utf-8', 'replace')
    return set(re.findall(r'\bambx?-[a-z0-9-]+\b', text)) | {'ambient'}

def split_rules(css):
    """Top-level CSS rules as (selector/prelude, body) with nesting kept in body."""
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find('{', i)
        if j < 0: break
        prelude = css[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth:
            if css[k] == '{': depth += 1
            elif css[k] == '}': depth -= 1
            k += 1
        out.append((prelude, css[j + 1:k - 1]))
        i = k
    return out

def purge_ambient(css, used):
    """Drop rules whose selectors only name Ambient classes the page never uses.
    Everything else (at-rules, :root, *, element selectors, used classes) stays."""
    kept, dropped = [], 0
    for prelude, body in split_rules(css):
        if prelude.startswith('@'):
            kept.append('%s{%s}' % (prelude, body)); continue
        classes = set(re.findall(r'\.(ambx?-[a-z0-9-]+|ambient)\b', prelude))
        if classes and not (classes & used):
            dropped += 1; continue
        kept.append('%s{%s}' % (prelude, body))
    return ''.join(kept), dropped

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join(ROOT, '..', 'orbit', 'src', 'web_bundle.h'))
    ap.add_argument('--dist', default=os.path.join(ROOT, 'dist'))
    a = ap.parse_args()
    used = used_ambient_classes()
    entries, total_raw, total_gz = [], 0, 0
    for route, src, mime in FILES:
        data = read(src)
        if src == 'ambient.css':
            css, dropped = purge_ambient(data.decode('utf-8'), used)
            print('ambient.css: kept %d used classes, dropped %d unused rules' % (len(used), dropped))
            data = css.encode('utf-8')
        if src == 'index.html':
            data = re.sub(rb'\?v=[0-9.]+', b'', data)                      # the firmware version is the cache key
            data = re.sub(rb'<link rel="preconnect"[^>]*>\s*', b'', data)  # no internet on the pedal's AP
            data = re.sub(rb'<link href="https://fonts\.googleapis\.com[^>]*>\s*', b'', data)
        dist_path = os.path.join(a.dist, src)
        os.makedirs(os.path.dirname(dist_path), exist_ok=True)
        with open(dist_path, 'wb') as f: f.write(data)
        gz = gzip.compress(data, 9, mtime=0)
        entries.append((route, mime, gz, len(data)))
        total_raw += len(data); total_gz += len(gz)
        print('  %-18s %7d raw  %7d gz' % (route, len(data), len(gz)))
    print('total %d raw, %d gzipped' % (total_raw, total_gz))

    lines = ['// AUTO-GENERATED by orbit_ui/tools/bundle.py -- DO NOT EDIT.',
             '// orbit_ui served by the pedal: %d files, %d bytes raw, %d gzipped.' % (len(entries), total_raw, total_gz),
             '#pragma once', '#include <cstddef>', '#include <cstdint>', '#include <pgmspace.h>', '',
             'struct WebFile { const char* path; const char* mime; const uint8_t* gz; size_t len; };', '']
    for i, (route, mime, gz, raw) in enumerate(entries):
        lines.append('// %s (%d raw)' % (route, raw))
        lines.append('static const uint8_t kWebGz%d[] PROGMEM = {' % i)
        for j in range(0, len(gz), 24):
            lines.append('  ' + ''.join('0x%02X,' % b for b in gz[j:j + 24]))
        lines.append('};')
    lines.append('')
    lines.append('constexpr size_t kWebFileCount = %d;' % len(entries))
    lines.append('static const WebFile kWebFiles[kWebFileCount] = {')
    for i, (route, mime, gz, raw) in enumerate(entries):
        lines.append('  { "%s", "%s", kWebGz%d, %d },' % (route, mime, i, len(gz)))
    lines.append('};')
    lines.append('')
    out = os.path.abspath(a.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', newline='\n') as f: f.write('\n'.join(lines))
    print('wrote', out, '(%d KB)' % (os.path.getsize(out) // 1024))

if __name__ == '__main__':
    main()
